import vm from 'node:vm';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../assets/js/analytics.js',import.meta.url),'utf8');
const scripts=[], listeners={};
const window={}; window.self=window;window.top=window;
const document={scripts,referrer:'',head:{append:s=>scripts.push(s)},createElement:()=>({dataset:{}}),querySelectorAll:()=>[{textContent:JSON.stringify({'@type':'SportsEvent','@id':'match-1',name:'Match',startDate:'2026-09-26'})}],addEventListener:(n,fn)=>listeners[n]=fn};
const context=vm.createContext({window,document,location:{hostname:'rugby2027.ru',pathname:'/match-center/',href:'https://rugby2027.ru/match-center/'},URL});
vm.runInContext(source,context);vm.runInContext(source,context);
const calls=()=>window.ym.a.map(a=>Array.from(a));
assert.equal(scripts.length,1);assert.equal(calls().filter(a=>a[1]==='init').length,1);
for(const key of ['webvisor','clickmap','trackLinks','accurateTrackBounce'])assert.equal(calls()[0][2][key],true);
assert.equal(calls().filter(a=>a[2]==='match_open').length,1);
listeners['rugby:player-open']({detail:{playerId:'ellis-genge'}});
assert.equal(calls().at(-1)[2],'player_card_open');
listeners.click({target:{closest:()=>({matches:s=>s==='a',href:'https://danilexpert.taplink.ws/p/1105f4c/?refLinkId=246672',getAttribute:()=>''})}});
assert.equal(calls().at(-1)[2],'balance_click');
listeners.click({target:{closest:()=>({matches:s=>s==='#copySupportCard'})}});
assert.equal(calls().at(-1)[3].action,'copy_attempt');
window.ym=()=>{throw new Error('blocked');};
assert.doesNotThrow(()=>listeners['rugby:player-open']({detail:{playerId:'test'}}));
console.log('Analytics: single init/script, match identity, interaction goals, fail-safe verified.');
